AgileDevelopment/Models/Member.cs
using System.ComponentModel.DataAnnotations;

namespace AgileDevelopment.Models
{
    public class Member
    {
        public int MemberID { get; set; }
        public string Title { get; set; }
        public string? Description { get; set; }

        [Display(Name = "Methodology")]
        public int MethodologyID { get; set; }
        public Methodology? Methodology { get; set; }
        public ICollection<MindSet>? MindSets { get; set; }

    }
}

AgileDevelopment/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgileDevelopment.Data;
using AgileDevelopment.Models;
using AgileDevelopment.Services;

namespace AgileDevelopment.Controllers
{
    public class MembersController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly IMemberService _memberService;

        public MembersController(ApplicationContext context, IMemberService memberService)
        {
            _context = context;
            _memberService = memberService;
        }

        // GET: Members
        public async Task<IActionResult> Index()
        {
              return _context.Member != null ? 
                          View(await _context.Member.ToListAsync()) :
                          Problem("Entity set 'ApplicationContext.Member'  is null.");
        }

        public async Task<IActionResult> ListMembers(int id)
        {
            var members = await _context.Member.ToListAsync();

            return _context.Member != null ?
                        //View("Index", await _context.Member.Where(m => m.MethodologyID == id).ToListAsync()) :
                        View("Index", _memberService.FilterMemberById(id, members)):
                        Problem("Entity set 'ApplicationContext.Member'  is null.");
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Member == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .FirstOrDefaultAsync(m => m.MemberID == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            ViewData["MethodologyId"] = new SelectList(_context.Methodology.ToList(),"MethodologyID", "Title");
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberID,Title,Description,MethodologyID")] Member member)
        {
            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Member == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FindAsync(id);
            ViewData["MethodologyId"] = new SelectList(_context.Methodology.ToList(),"MethodologyID", "Title");
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberID,Title,Description,MethodologyID")] Member member)
        {
            if (id != member.MemberID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.MemberID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Member == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .FirstOrDefaultAsync(m => m.MemberID == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Member == null)
            {
                return Problem("Entity set 'ApplicationContext.Member'  is null.");
            }
            var member = await _context.Member.FindAsync(id);
            if (member != null)
            {
                _context.Member.Remove(member);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(int id)
        {
          return (_context.Member?.Any(e => e.MemberID == id)).GetValueOrDefault();
        }
    }
}

AgileDevelopment/Controllers/MethodologiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgileDevelopment.Data;
using AgileDevelopment.Models;

namespace AgileDevelopment.Controllers
{
    public class MethodologiesController : Controller
    {
        private readonly ApplicationContext _context;

        public MethodologiesController(ApplicationContext context)
        {
            _context = context;
        }


        // GET: Methodologies
        public async Task<IActionResult> Index()
        {
              return _context.Methodology != null ? 
                          View(await _context.Methodology.ToListAsync()) :
                          Problem("Entity set 'ApplicationContext.Methodology'  is null.");
        }

        // GET: Methodologies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Methodology == null)
            {
                return NotFound();
            }

            var methodology = await _context.Methodology
                .FirstOrDefaultAsync(m => m.MethodologyID == id);
            if (methodology == null)
            {
                return NotFound();
            }

            return View(methodology);
        }

        // GET: Methodologies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Methodologies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MethodologyID,Title,Description")] Methodology methodology)
        {
            if (ModelState.IsValid)
            {
                _context.Add(methodology);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(methodology);
        }

        // GET: Methodologies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Methodology == null)
            {
                return NotFound();
            }

            var methodology = await _context.Methodology.FindAsync(id);
            if (methodology == null)
            {
                return NotFound();
            }
            return View(methodology);
        }

        // POST: Methodologies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MethodologyID,Title,Description")] Methodology methodology)
        {
            if (id != methodology.MethodologyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(methodology);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MethodologyExists(methodology.MethodologyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(methodology);
        }

        // GET: Methodologies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Methodology == null)
            {
                return NotFound();
            }

            var methodology = await _context.Methodology
                .FirstOrDefaultAsync(m => m.MethodologyID == id);
            if (methodology == null)
            {
                return NotFound();
            }

            return View(methodology);
        }

        // POST: Methodologies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Methodology == null)
            {
                return Problem("Entity set 'ApplicationContext.Methodology'  is null.");
            }
            var methodology = await _context.Methodology.FindAsync(id);
            if (methodology != null)
            {
                _context.Methodology.Remove(methodology);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MethodologyExists(int id)
        {
          return (_context.Methodology?.Any(e => e.MethodologyID == id)).GetValueOrDefault();
        }
    }
}

AgileDevelopment/Controllers/MindSetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgileDevelopment.Data;
using AgileDevelopment.Models;
using AgileDevelopment.Services;

namespace AgileDevelopment.Controllers
{
    public class MindSetsController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly IMindSetService _mindSetService;

        public MindSetsController(ApplicationContext context, IMindSetService mindSetService)
        {
            _context = context;
            _mindSetService = mindSetService;
        }

        // GET: MindSets
        public async Task<IActionResult> Index()
        {
            return _context.MindSet != null ?
                        View(await _context.MindSet.ToListAsync()) :
                        Problem("Entity set 'ApplicationContext.MindSet'  is null.");
        }
        public async Task<IActionResult> ListMindSets(int id, int methodologyId)
        {
            var mindSets = await _context.MindSet.ToListAsync();
            return _context.MindSet != null ?
                       // View("Index", await _context.MindSet.Where(ms => ms.MemberID == id && ms.Member.MethodologyID == methodologyId).ToListAsync()) :
                       View("Index", _mindSetService.FilterMindSetsByMemberId(id, mindSets)) :
                        Problem("Entity set 'ApplicationContext.MindSet'  is null.");
        }

        // GET: MindSets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MindSet == null)
            {
                return NotFound();
            }

            var mindSet = await _context.MindSet
                .FirstOrDefaultAsync(m => m.MindSetID == id);
            if (mindSet == null)
            {
                return NotFound();
            }

            return View(mindSet);
        }

        // GET: MindSets/Create
        public IActionResult Create()
        {
            ViewData["MemberId"] = new SelectList(_context.Member.ToList(), "MemberID", "Title");
            return View();
        }

        // POST: MindSets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MindSetID,Title,Description,MemberID")] MindSet mindSet)
        {
            Member member = await _context.Member.FirstOrDefaultAsync(m => m.MemberID == mindSet.MemberID);
            mindSet.Member = member;
            if (ModelState.IsValid)
            {
                _context.Add(mindSet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mindSet);
        }

        // GET: MindSets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MindSet == null)
            {
                return NotFound();
            }

            var mindSet = await _context.MindSet.FindAsync(id);
            ViewData["MemberId"] = new SelectList(_context.Member.ToList(), "MemberID", "Title");
            if (mindSet == null)
            {
                return NotFound();
            }
            return View(mindSet);
        }

        // POST: MindSets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MindSetID,Title,Description,MemberID")] MindSet mindSet)
        {
            Member member = await _context.Member.FirstOrDefaultAsync(m => m.MemberID == mindSet.MemberID);
            mindSet.Member = member;
            if (id != mindSet.MindSetID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mindSet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MindSetExists(mindSet.MindSetID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mindSet);
        }

        // GET: MindSets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MindSet == null)
            {
                return NotFound();
            }

            var mindSet = await _context.MindSet
                .FirstOrDefaultAsync(m => m.MindSetID == id);
            if (mindSet == null)
            {
                return NotFound();
            }

            return View(mindSet);
        }

        // POST: MindSets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MindSet == null)
            {
                return Problem("Entity set 'ApplicationContext.MindSet'  is null.");
            }
            var mindSet = await _context.MindSet.FindAsync(id);
            if (mindSet != null)
            {
                _context.MindSet.Remove(mindSet);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MindSetExists(int id)
        {
            return (_context.MindSet?.Any(e => e.MindSetID == id)).GetValueOrDefault();
        }
    }
}

AgileDevelopment/Views/Members/Create.cshtml
@model AgileDevelopment.Models.Member

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="MethodologyID" class="control-label"></label>
                <select asp-for="MethodologyID" class="form-control" asp-items="ViewBag.MethodologyId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AgileDevelopment/Views/Members/Delete.cshtml
@model AgileDevelopment.Models.Member

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MemberID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AgileDevelopment/Views/Members/Details.cshtml
@model AgileDevelopment.Models.Member

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MemberID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<div>
    <a asp-controller="MindSets" asp-action="ListMindSets" asp-route-id="@Model?.MemberID"><button class="btn btn-primary">
        @Html.DisplayFor(model => model.Title) Member MindSets
    </button></a>
</div>

AgileDevelopment/Views/Members/Edit.cshtml
@model AgileDevelopment.Models.Member

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MemberID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="MethodologyID" class="control-label"></label>
                <select asp-for="MethodologyID" class="form-control" asp-items="ViewBag.MethodologyId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AgileDevelopment/Views/Members/Index.cshtml
@model IEnumerable<AgileDevelopment.Models.Member>

@{
	ViewData["Title"] = "Members";
}

<h1>@ViewBag.Title</h1>

<p>
	<a asp-action="Create">Create New</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Title)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Description)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					<a asp-action="Details" asp-route-id="@item.MemberID">@Html.DisplayFor(modelItem => item.Title)</a>
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Description)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.MemberID">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.MemberID">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.MemberID">Delete</a>
				</td>
			</tr>
		}
	</tbody>

</table>
<div>
	<a asp-controller="Methodologies" asp-action="Index">Back_to_Home</a>
</div>